export const FETCH_COMPLETED_ORDERS = 'FETCH_COMPLETED_ORDERS';
export const FETCH_ACCEPTED_ORDERS = 'FETCH_ACCEPTED_ORDERS';
export const FETCH_PENDING_ORDERS = 'FETCH_PENDING_ORDERS';
export const FETCH_PREPARED_ORDERS = 'FETCH_PREPARED_ORDERS';
export const FETCH_CANCELLED_ORDERS = 'FETCH_CANCELLED_ORDERS';
export const FETCH_PENDING_ORDERS_ERROR = 'FETCH_PENDING_ORDERS_ERROR';
export const FETCH_ACCEPTED_ORDERS_ERROR = 'FETCH_ACCEPTED_ORDERS_ERROR';
export const FETCH_CANCELLED_ORDERS_ERROR = 'FETCH_CANCELLED_ORDERS_ERROR';
